import { TestCase } from "./testcase";

 // Represents the complete execution plan generated by the AI Planner. 
 // One user request can produce multiple test cases.
 
export interface ExecutionPlan {
  
   // Overall objective provided by the user. Example: "Validate Login Functionality"  
  objective: string;
  
  // AI-generated execution summary.  
  summary?: string;
  
  // ISO timestamp indicating when the plan was generated.
  generatedAt: string;
  
  // AI model used to generate the plan. Example: llama3, qwen3, gpt-5
  generatedBy?: string;
  
  // Collection of test cases.
  testCases: TestCase[];

}