import { Browser, BrowserContext, Page } from "playwright";
import { z, ZodType } from "zod";

// Generic JSON object.
export type JsonObject = Record<string, unknown>;

// Shared Playwright browser session.
export interface BrowserSessionContext {
    browser: Browser | null;
    context: BrowserContext | null;
    page: Page | null;
}

// Tool execution status.
export enum ToolStatus {
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
}

// Standard tool result.
export interface ToolResult {
    status: ToolStatus;
    message: string;
    data?: JsonObject;
}

// Tool execution context.
export interface ToolContext<TArgs extends JsonObject = JsonObject, > {
    session: BrowserSessionContext;
    args: TArgs;
}

// Definition of one executable MCP Tool.
export interface ToolDefinition<TArgs extends JsonObject = JsonObject, > {
    // Unique tool name.
    name: string;
    // Human readable description of the tool.
    description: string;
    // Runtime validation schema using Zod.
    schema: ZodType<TArgs>;
    // Execute tool with provided context and arguments.
    execute(
        context: ToolContext<TArgs>,
    ): Promise<ToolResult>;
}

// One execution step generated by AI Planner.
export interface ExecutionStep {
    tool: string;
    arguments: JsonObject;
}

// Complete execution plan generated by AI Planner.
export interface ExecutionPlan {
    steps: ExecutionStep[];
}

// Result of one executed step.
export interface StepExecutionResult {
    step: ExecutionStep;
    result: ToolResult;
    startedAt: Date;
    finishedAt: Date;
}

// Runtime execution context.
export interface ExecutionContext {
    session: BrowserSessionContext;
    currentStep?: ExecutionStep;
    variables: Map<string, unknown>;
}

// Hook executed before/after tool execution.
export type ToolHook = (
    context: ExecutionContext,
    step: ExecutionStep,
) => Promise<void>;

// Helper type for inferring arguments from a Zod schema.
export type InferToolArgs<TSchema extends ZodType> = z.infer<TSchema>;