/*
 * LLM Client
 *
 * Responsible for communicating with the configured LLM provider.
 *
 * Current Provider:
 * - Ollama
 *
 * Responsibilities:
 * - Send prompt to LLM
 * - Receive response
 * - Handle HTTP errors
 * * This class does NOT:
 * - Parse JSON
 * - Validate ExecutionPlan
 * - Contain business logic
 */

export interface LLMClientConfig {
  /*
   * Ollama endpoint.
   *
   * Example:
   * http://localhost:11434/api/generate
   */
  endpoint: string;

  /*
   * Model name.
   *
   * Example:
   * llama3
   * qwen3
   */
  model: string;

  /**
   * Request timeout (milliseconds).
   */
  timeout?: number;
}

interface OllamaGenerateResponse {
  response: string;
  done: boolean;
}

export class LLMClient {
  private readonly endpoint: string;
  private readonly model: string;
  private readonly timeout: number;

  constructor(config: LLMClientConfig) {
    this.endpoint = config.endpoint;
    this.model = config.model;
    this.timeout = config.timeout ?? 60000;
  }

  /**
   * Sends a prompt to the configured LLM.
   *
   * @param prompt Full prompt generated by PromptBuilder.
   * @returns Raw response from the LLM.
   */
  public async generate(prompt: string): Promise<string> {
    const controller = new AbortController();

    const timeout = setTimeout(() => {
      controller.abort();
    }, this.timeout);

    try {
      const response = await fetch(this.endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        signal: controller.signal,
        body: JSON.stringify({
          model: this.model,
          prompt,
          stream: false
        })
      });

      if (!response.ok) {
        throw new Error(
          `LLM request failed (${response.status} ${response.statusText})`
        );
      }

      const data = (await response.json()) as OllamaGenerateResponse;

      if (!data.response) {
        throw new Error("LLM returned an empty response.");
      }

      return data.response.trim();
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`LLM Client Error: ${error.message}`);
      }

      throw new Error("Unknown LLM Client error.");
    } finally {
      clearTimeout(timeout);
    }
  }
}